apiVersion: apps/v1
kind: Deployment
metadata:
  name: idmouse
  labels:
    app: idmouse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idmouse
  template:
    metadata:
      labels:
        app: idmouse
    spec:
      serviceAccountName: idmouse
      containers:
        - name: idmouse
          securityContext:
            allowPrivilegeEscalation: false
          image: packages.buildkite.com/nresare/idmouse/idmouse:0.2.1-9003cca4
          ports:
            - name: http
              containerPort: 8080
