# App configurations reference releases defined in releases.yaml.
# The release provides the chart source (repo, chart name, version).

[[helm]]
namespace = "cert-manager"
release = "cert-manager"
values = ["cert-manager/values.yaml"]
extra-resources = "cert-manager/extra"

[[helm]]
namespace = "surrealdb"
release = "surrealdb"
init = "surrealdb/fix-permissions.sh"
values = ["surrealdb/values.yaml"]

[[helm]]
namespace = "teleport-cluster"
release = "teleport-cluster"
values = ["teleport/cluster-values.yaml"]
extra-resources = "teleport/extra"

[[helm]]
namespace = "teleport"
release = "teleport-kube-agent"
values = ["teleport/agent-values.yaml"]

[[helm]]
namespace = "envoy-gateway-system"
release = "envoy-gateway"
extra-resources = "envoy-gateway/extra"

[[helm]]
namespace = "envoy-gateway-system"
release = "envoy-gateway-crds"
values = ["envoy/crds-values.yaml"]

[[helm]]
namespace = "metrics-server"
release = "metrics-server"

[[website]]
name = "zq.lu"
namespace = "web"
hugo-repo = "https://github.com/nresare/zq.lu"

[[website]]
name = "noa.re"
namespace = "web"
hugo-repo = "https://github.com/nresare/noa.re"
extra-hostnames = "nadia.resare.com"

[[website]]
name = "relcoord.noa.re"
namespace = "relcoord"
replicas = 2
image = "repo.noa.re/relcoord:0.1.0-edebcc58"
config = { "/config/relcoord.toml" = "relcoord/relcoord.toml"}
custom-token-audiences = ["idmouse", "idcat.noa.re"]

[[copy]]
namespace = "acme-dns"
source = "acme-dns/manifests"
[[copy.config]]
"/etc/acme-dns/config.cfg" = "acme-dns/config.cfg"
