# App configurations reference releases defined in releases.yaml.
# The release provides the chart source (repo, chart name, version).

[[helm]]
namespace = "cert-manager"
release = "cert-manager"
values = ["cert-manager/values.yaml"]
extra-resources = "cert-manager/extra"

[[helm]]
namespace = "surrealdb"
release = "surrealdb"
init = "surrealdb/fix-permissions.sh"
values = ["surrealdb/values.yaml"]

[[helm]]
namespace = "teleport-cluster"
release = "teleport-cluster"
values = ["teleport/cluster-values.yaml"]
extra-resources = "teleport/extra"

[[helm]]
namespace = "teleport"
release = "teleport-kube-agent"
values = ["teleport/agent-values.yaml"]

[[helm]]
namespace = "envoy-gateway-system"
release = "envoy-gateway"
extra-resources = "envoy-gateway/extra"

[[website]]
name = "zq.lu"
namespace = "web"
hugo-repo = "https://github.com/nresare/zq.lu"

[[website]]
name = "noa.re"
namespace = "web"
hugo-repo = "https://github.com/nresare/noa.re"
extra-hostnames = "nadia.resare.com"

[[website]]
name = "id.noa.re"
namespace = "idelephant"
replicas = 1
image = "packages.buildkite.com/nresare/idelephant/idelephant:v0.2.3-rc.22-g2ac5be9"
args = ["-c", "/config/idelephant.toml"]
custom-token-audience = "idmouse"
external-secrets = [
    "/db-password",
    "/email-password",
]
[website.config]
"/config/idelephant.toml" = "idelephant/idelephant.toml"

[[website]]
name = "demo.resare.com"
namespace = "demo"
image = "nresare/oidc-client-demo:latest"
[website.config]
"/config/config.toml" = "demo/config.toml"

[[simple]]
namespace = "acme-dns"
copy-from = "acme-dns/manifests"
[[simple.config]]
"/etc/acme-dns/config.cfg" = "acme-dns/config.cfg"

[[simple]]
namespace = "idmouse"
copy-from = "idmouse/manifests"
[[simple.config]]
"/config/idmouse.toml" = "idmouse/idmouse.toml"
