image:
  tag: v3.0.5
persistence:
  enabled: true
strategy:
  type: Recreate
surrealdb:
  path: surrealkv://data/db
  log: debug
podExtraEnv:
  - name: SURREAL_CAPS_ALLOW_NET
    value: idmouse.idmouse.svc
